name: Lint

on:
  # Run on pushes to select branches and on all pull requests.
  push:
    branches:
      - main
      - develop
      - 'release/[0-9]+.[0-9]+*'
      - 'hotfix/[0-9]+.[0-9]+*'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Lint against the highest/lowest supported versions of each PHP major.
        # And also do a run against "nightly" (the current dev version of PHP).
        php_version: ['8.1', '8.2', '8.3']

    name: "Lint: PHP ${{ matrix.php_version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP for the composer install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      # The lint stage doesn't use code style, so no need for WPCS or phpcompatibility.
      - name: 'Composer: adjust dependencies - remove PHPCompatibility'
        run: composer remove --no-update --dev phpcompatibility/phpcompatibility-wp --no-scripts --no-interaction
      - name: 'Composer: adjust dependencies - remove WPCS'
        run: composer remove --no-update --dev wp-coding-standards/wpcs --no-scripts --no-interaction

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          # Use run id so no shell-specific date expansion is required here.
          custom-cache-suffix: ${{ github.run_id }}

      - name: Install PHP for the actual test
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none

      - name: Lint against parse errors
        run: composer lint -- --checkstyle > ./lint-report.xml || true

      - name: Install cs2pr and show lint results in PR
        if: ${{ always() }}
        run: |
          composer global require --no-interaction staabm/cs2pr
          if [ -x "$HOME/.composer/vendor/bin/cs2pr" ]; then
            $HOME/.composer/vendor/bin/cs2pr ./lint-report.xml || true
          elif [ -x "$HOME/.config/composer/vendor/bin/cs2pr" ]; then
            $HOME/.config/composer/vendor/bin/cs2pr ./lint-report.xml || true
          elif [ -x "vendor/bin/cs2pr" ]; then
            vendor/bin/cs2pr ./lint-report.xml || true
          else
            echo "cs2pr binary not found after install" && exit 0
          fi

      - name: Lint blueprint file
        run: composer lint-blueprint
